### ISSUE TITLE
Relative path errors

### ISSUE THREAD

**Issue by tfarina** [damian-m-g/xlsx_drone#4]
I have got the following error:
XLSX_C ERROR: "\xl\styles.xml" can't be parsed or doesn't exist.
XLSX_C ERROR: Index out of bounds.

I think it is because of these:
#define REL_PATH_TO_STYLES "\\xl\\styles.xml"
#define REL_PATH_TO_SHARED_STRINGS "\\xl\\sharedStrings.xml"
#define REL_PATH_TO_WORKBOOK "\\xl\\workbook.xml"
#define REL_PATH_TO_WORKSHEETS "\\xl\\worksheets\\"                                                                                                         

On linux, the paths use forward slashes '/'.

I have changed to the following and it seems to work:
+#define REL_PATH_TO_STYLES "/xl/styles.xml"
+#define REL_PATH_TO_SHARED_STRINGS "/xl/sharedStrings.xml"
+#define REL_PATH_TO_WORKBOOK "/xl/workbook.xml"
+#define REL_PATH_TO_WORKSHEETS "/xl/worksheets/"

**Comment by damian-m-g** [comment]
Hello @tfarina , thanks for reporting this problem, and also for providing the fix. It's implemented on this [commit](https://github.com/damian-m-g/xlsx_drone/commit/258a1bf7c0b378479c7f8a93eea37fe7e6a11279). Also, a [release](https://github.com/damian-m-g/xlsx_drone/releases/tag/0.2.4) with this commit included was done.
