### ISSUE TITLE
Parsing double and locale

### ISSUE THREAD

**Issue by gvollant** [damian-m-g/xlsx_drone#5]
The function set_cell_data_values_for_number in xlsx_drone call strtod.

Unfortunatelly, on a french system (locale with "," and not "." as decimal separator) , only the integer porting is used.

pehaps _atof_l is the solution

**Comment by damian-m-g** [comment]
Thank you very much @gvollant for detecting this problem and for the suggestion.

I see some style-related issues (different style than the rest of the code) with the pull request, other than that, it could be good to go. Sadly, I don't have available time during these days to take a closer look and correct those few things, but I'll try on next weeks. Cheers.

**Comment by gvollant** [comment]
I made a new PR #10 (same code, but with function header documentation)

**Comment by damian-m-g** [comment]
PR was very useful, thank you for insight. This issue has been fixed in 9a9db6edb36f900bf1ea761362f29a05f0c6ca10.
